version: '3.9'

volumes:
  nifi-db:
  nifi-flow:
  nifi-content:
  nifi-provenance:
  nifi-state:
  nifi-logs:
  nifi-registry-db:

networks:
  nifi-net:
  kafka_kafka-net:
    external: true

services:

  zookeeper:
    hostname: zookeeper
    image: confluentinc/cp-zookeeper
    restart: on-failure
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
    networks:
      - nifi-net

  nifi:
    hostname: nifi
    restart: on-failure
    ports:
      # HTTP
      - 8085:8080/tcp
      # HTTPS
      - 8443:8443/tcp
      # Remote Input Socket
      - 10000:10000/tcp
      # JVM Debugger
      - 8002:8000/tcp
      # Cluster Node Protocol
      #- 11443:11443/tcp
    volumes:
      # mkdir /var/lib/nifi && chown -R 1000:1000 /var/lib/nifi
      - nifi-db:/opt/nifi/nifi-current/database_repository
      - nifi-flow:/opt/nifi/nifi-current/flowfile_repository
      - nifi-content:/opt/nifi/nifi-current/content_repository
      - nifi-provenance:/opt/nifi/nifi-current/provenance_repository
      - nifi-state:/opt/nifi/nifi-current/state
      - nifi-logs:/opt/nifi/nifi-current/logs
      
      # A custom nifi.properties file can be mounted as follows.
      #- /var/lib/nifi/conf/nifi.properties:/opt/nifi/nifi-current/conf/nifi.properties:ro
    image: 'apache/nifi:latest'
    environment:
      NIFI_WEB_HTTP_HOST: '0.0.0.0'
      NIFI_WEB_HTTP_PORT: 8080
      NIFI_CLUSTER_IS_NODE: true
      NIFI_CLUSTER_NODE_PROTOCOL_PORT: 8082
      NIFI_ZK_CONNECT_STRING: zookeeper:2181
      NIFI_ELECTION_MAX_WAIT: 30 sec
      NIFI_SENSITIVE_PROPS_KEY: 12345678901234567890A
    networks:
      - nifi-net
      - kafka_kafka-net
      
  nifi-registry:
    hostname: nifi-registry
    restart: on-failure
    depends_on:
      - nifi-registry-db
    ports:
        - '18080:18080'
    image: 'apache/nifi-registry:latest'
    environment:
      - NIFI_REGISTRY_DB_URL=jdbc:postgresql://database:5432/nifi_reg
      - NIFI_REGISTRY_DB_CLASS=org.postgresql.Driver
      - NIFI_REGISTRY_DB_DIR=/opt/nifi-registry/current/lib/
      - NIFI_REGISTRY_DB_USER=nifi
      - NIFI_REGISTRY_DB_PASS=nifi
      - NIFI_REGISTRY_FLOW_PROVIDER=file
      - NIFI_REGISTRY_FLOW_STORAGE_DIR=/opt/nifi-registry/nifi-registry-current/flow_storage
    networks:
      - nifi-net
    volumes:
      - ./postgresql-42.2.2.jar:/opt/nifi-registry/current/lib/postgresql-42.2.2.jar
      - type: bind
        source: ./storage/flows
        target: /opt/nifi-registry/nifi-registry-current/flow_storage

  nifi-registry-db:
    hostname: database
    image: postgres:12
    restart: always
    environment:
      - POSTGRES_USER=nifi
      - POSTGRES_PASSWORD=nifi
      - POSTGRES_DB=nifi_reg
    volumes:
      - nifi-registry-db:/var/lib/postgresql/data/
    networks:
      - nifi-net