version: '3.5'

volumes:
  zookeeper-data:
  zookeeper-log:
  kafka-data:

services:

    ####
    #
    # BASE: https://github.com/vdesabou/kafka-docker-playground/blob/master/environment/plaintext/docker-compose.yml
    # OVERRIDES: https://github.com/vdesabou/kafka-docker-playground/blob/master/environment/sasl-plain/docker-compose.yml
    #
    ####

    zookeeper:
        image: confluentinc/cp-zookeeper
        hostname: zookeeper
        restart: always
        volumes:
        - ./zookeeper.jaas.conf:/etc/kafka/zookeeper_server_jaas.conf
        - zookeeper-data:/var/lib/zookeeper/data:Z
        - zookeeper-log:/var/lib/zookeeper/log:Z
        environment:
            ZOOKEEPER_CLIENT_PORT: 2181
            ZOOKEEPER_TICK_TIME: 2000
            KAFKA_OPTS: -Djava.security.auth.login.config=/etc/kafka/zookeeper_server_jaas.conf
                -Dzookeeper.authProvider.1=org.apache.zookeeper.server.auth.SASLAuthenticationProvider
                -Dzookeeper.allowSaslFailedClients=false
                -Dzookeeper.requireClientAuthScheme=sasl

    broker:
        image: confluentinc/cp-kafka
        hostname: broker
        restart: always
        ports:
          - "9092:9092"
          - "29092:29092"
          # - "10000:10000"
        volumes:
          - kafka-data:/var/lib/kafka/data:Z
          - ./kafka.jaas.conf:/etc/kafka/kafka_server_jaas.conf
        environment:
            KAFKA_BROKER_ID: 1
            KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: BROKER:SASL_PLAINTEXT,HOST:SASL_PLAINTEXT
            KAFKA_LISTENERS: BROKER://:9092,HOST://:29092
            KAFKA_ADVERTISED_LISTENERS: BROKER://broker:9092,HOST://localhost:29092
            KAFKA_LISTENER_NAME_BROKER_SASL_ENABLED_MECHANISMS: PLAIN
            KAFKA_LISTENER_NAME_BROKER_PLAIN_SASL_JAAS_CONFIG: |
                    org.apache.kafka.common.security.plain.PlainLoginModule required \
                    username="broker" \
                    password="broker" \
                    user_broker="broker" \
                    user_akhq="akhq-secret" \
                    user_schemaregistry="schemaregistry-secret" \
                    user_connect="connect-secret" \
                    user_sftp="sftp-secret" \
                    user_client="client-secret";
            KAFKA_LISTENER_NAME_HOST_SASL_ENABLED_MECHANISMS: PLAIN
            KAFKA_LISTENER_NAME_HOST_PLAIN_SASL_JAAS_CONFIG: |
                    org.apache.kafka.common.security.plain.PlainLoginModule required \
                    username="broker" \
                    password="broker" \
                    user_broker="broker" \
                    user_akhq="akhq-secret" \
                    user_schemaregistry="schemaregistry-secret" \
                    user_connect="connect-secret" \
                    user_sftp="sftp-secret" \
                    user_client="client-secret";
            KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: PLAIN
            KAFKA_INTER_BROKER_LISTENER_NAME: BROKER
            CONFLUENT_METRICS_REPORTER_SASL_MECHANISM: PLAIN
            CONFLUENT_METRICS_REPORTER_SECURITY_PROTOCOL: SASL_PLAINTEXT
            CONFLUENT_METRICS_REPORTER_SASL_JAAS_CONFIG: "org.apache.kafka.common.security.plain.PlainLoginModule required \
                username=\"client\" \
                password=\"client-secret\";"
            KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
            KAFKA_AUTHORIZER_CLASS_NAME: 'kafka.security.authorizer.AclAuthorizer'
            KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: 'true'
            KAFKA_OPTS: "-Djava.security.auth.login.config=/etc/kafka/kafka_server_jaas.conf"

    connect:
        image: confluentinc/cp-kafka-connect
        hostname: connect
        restart: always
        depends_on:
          - broker
          - schema-registry
        ports:
          - "5005:5005"
          - "8083:8083"
          - "10002:10002"
        environment:
            CONNECT_BOOTSTRAP_SERVERS: 'broker:9092'
            CONNECT_REST_ADVERTISED_HOST_NAME: connect
            CONNECT_GROUP_ID: "connect-cluster"
            CONNECT_PRODUCER_CLIENT_ID: "connect-worker-producer"
            CONNECT_CONFIG_STORAGE_TOPIC: connect-configs
            CONNECT_OFFSET_STORAGE_TOPIC: connect-offsets
            CONNECT_STATUS_STORAGE_TOPIC: connect-status
            CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: 1
            CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: 1
            CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: 1
            CONNECT_KEY_CONVERTER: "org.apache.kafka.connect.storage.StringConverter"
            CONNECT_VALUE_CONVERTER: "io.confluent.connect.avro.AvroConverter"
            CONNECT_VALUE_CONVERTER_SCHEMAS_ENABLE: "false"
            CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL: "http://schema-registry:8081"
            CONNECT_INTERNAL_KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
            CONNECT_INTERNAL_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
            CONNECT_PLUGIN_PATH: /usr/share/confluent-hub-components/confluentinc-kafka-connect-s3 # only load one connector to speed up deployment (it is overidden in connect tests)
            CONNECT_LOG4J_LOGGERS: org.apache.zookeeper=ERROR,org.I0Itec.zkclient=ERROR,org.reflections=ERROR
            # Externalizing Secrets
            CONNECT_CONFIG_PROVIDERS: 'file'
            CONNECT_CONFIG_PROVIDERS_FILE_CLASS: 'org.apache.kafka.common.config.provider.FileConfigProvider'
            # CONNECT_LOG4J_ROOT_LOGLEVEL: DEBUG
            # KIP-158 https://cwiki.apache.org/confluence/display/KAFKA/KIP-158%3A+Kafka+Connect+should+allow+source+connectors+to+set+topic-specific+settings+for+new+topics (6.x only)
            CONNECT_TOPIC_CREATION_ENABLE: 'true'
            CONNECT_CONNECTOR_CLIENT_CONFIG_OVERRIDE_POLICY: All
            CONNECT_LOG4J_APPENDER_STDOUT_LAYOUT_CONVERSIONPATTERN: "[%d] %p %X{connector.context}%m (%c:%L)%n"
            # Configure the Connect workers to use SASL/PLAIN.
            CONNECT_SASL_MECHANISM: PLAIN
            CONNECT_SECURITY_PROTOCOL: SASL_PLAINTEXT
            # JAAS
            CONNECT_SASL_JAAS_CONFIG: "org.apache.kafka.common.security.plain.PlainLoginModule required \
                username=\"connect\" \
                password=\"connect-secret\";"
            # producer
            CONNECT_PRODUCER_CONFLUENT_MONITORING_INTERCEPTOR_SECURITY_PROTOCOL: SASL_PLAINTEXT
            CONNECT_PRODUCER_CONFLUENT_MONITORING_INTERCEPTOR_SASL_JAAS_CONFIG: "org.apache.kafka.common.security.plain.PlainLoginModule required \
                username=\"connect\" \
                password=\"connect-secret\";"
            CONNECT_PRODUCER_CONFLUENT_MONITORING_INTERCEPTOR_SASL_MECHANISM: PLAIN
            # consumer
            CONNECT_CONSUMER_CONFLUENT_MONITORING_INTERCEPTOR_SECURITY_PROTOCOL: SASL_PLAINTEXT
            CONNECT_CONSUMER_CONFLUENT_MONITORING_INTERCEPTOR_SASL_JAAS_CONFIG: "org.apache.kafka.common.security.plain.PlainLoginModule required \
                username=\"connect\" \
                password=\"connect-secret\";"
            CONNECT_CONSUMER_CONFLUENT_MONITORING_INTERCEPTOR_SASL_MECHANISM: PLAIN
            # producer
            CONNECT_PRODUCER_SASL_MECHANISM: PLAIN
            CONNECT_PRODUCER_SECURITY_PROTOCOL: SASL_PLAINTEXT
            CONNECT_PRODUCER_SASL_JAAS_CONFIG: "org.apache.kafka.common.security.plain.PlainLoginModule required \
                username=\"connect\" \
                password=\"connect-secret\";"
            # consumer
            CONNECT_CONSUMER_SASL_MECHANISM: PLAIN
            CONNECT_CONSUMER_SECURITY_PROTOCOL: SASL_PLAINTEXT
            CONNECT_CONSUMER_SASL_JAAS_CONFIG: "org.apache.kafka.common.security.plain.PlainLoginModule required \
                username=\"connect\" \
                password=\"connect-secret\";"
            KAFKA_JVM_PERFORMANCE_OPTS: -server -XX:+UseG1GC -XX:GCTimeRatio=1
                  -XX:MinHeapFreeRatio=10 -XX:MaxHeapFreeRatio=20
                  -XX:MaxGCPauseMillis=10000 -XX:InitiatingHeapOccupancyPercent=35 -XX:+ExplicitGCInvokesConcurrent
                  -XX:MaxInlineLevel=15 -Djava.awt.headless=true

    schema-registry:
        image: confluentinc/cp-schema-registry
        hostname: schema-registry
        restart: always
        depends_on:
          - broker
        ports:
          - "8081:8081"
          - "10001:10001"
        environment:
            SCHEMA_REGISTRY_HOST_NAME: schema-registry
            SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081
            SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: broker:9092
            SCHEMA_REGISTRY_SCHEMA_PROVIDERS_AVRO_VALIDATE_DEFAULTS: "true"
            SCHEMA_REGISTRY_KAFKASTORE_SECURITY_PROTOCOL: SASL_PLAINTEXT
            SCHEMA_REGISTRY_KAFKASTORE_SASL_MECHANISM: PLAIN
            SCHEMA_REGISTRY_KAFKASTORE_SASL_JAAS_CONFIG: "org.apache.kafka.common.security.plain.PlainLoginModule required \
                username=\"schemaregistry\" \
                password=\"schemaregistry-secret\";"

    # todo: update for sals auth
    akhq:
        image: tchiotludo/akhq
        environment:
          AKHQ_CONFIGURATION: |
            akhq:
              connections:
                docker-kafka-server:
                  properties:
                    bootstrap.servers: "broker:9092"
                    security.protocol: SASL_PLAINTEXT
                    sasl.mechanism: PLAIN
                    # sasl.username: broker
                    # sasl.password: broker
                    sasl.jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username="akhq" password="akhq-secret";
                  # schema-registry:
                  #   url: "http://schema-registry:8081"
                  connect:
                    - name: "connect"
                      url: "http://connect:8083"

        ports:
          - 8080:8080